# Generated by Django 3.1.2 on 2020-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'Not rated yet'), (1, 'Not recommended'), (2, 'Okay'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
            ],
        ),
    ]
